# Generated by Django 4.1.3 on 2022-11-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], default='M', max_length=10)),
                ('birthday', models.DateField()),
                ('address', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('aff_school', models.CharField(default='', max_length=30)),
                ('class_level', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
